### ISSUE TITLE
Incorrect call to print_error

### ISSUE THREAD

**Issue by NeillM** [bozoh/moodle-mod_simplecertificate#126]
In the add_instance method of the simple certificate class in locallib.php print_erro is used instead of print_error:

```php
if (!$this->instance = $DB->get_record('simplecertificate', array('id' => $returnid), '*', MUST_EXIST)) {
     print_erro('certificatenot', 'simplecertificate');
}
```
Version: 2.2.1 for Moodle.2.7

It also seems to be present on the master branch

**Comment by NeillM** [comment]
Also found a similar issue in the update_instance method.

**Comment by NeillM** [comment]
And in the simplecertificate_reset_userdata function in lib.php

**Comment by bozoh** [comment]
My bad,  fixing it
