### ISSUE TITLE
Redirection to moodle homepage when trying to access module

### ISSUE THREAD

**Issue by nikmav** [bozoh/moodle-mod_simplecertificate#131]
Hello,

I have a strange thing happening whereby I click on the link to access the certificate module (url below):

http://mydomain.com.au/mod/simplecertificate/view.php?id=34

but instead of taking me to the module screen where I can send a test certificate, print certificates etc. it redirects to the homepage mydomain.com.au. I can however edit the certificate itself via the Edit option.

I'm running moodle 2.9.1 and the 29 version of simplecertificate.

Any ideas?  I have inherited this server.

Thanks

**Edit 1** - Apache log notes the following:

1.1.1.1 - - [29/Jul/2015:18:19:27 +1000] "GET /mod/simplecertificate/view.php?id=34 HTTP/1.1" 404 - "http://mydomain.com.au/course/view.php?id=2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:39.0) Gecko/20100101 Firefox/39.0" - This is not limited to Firefox.

In Firebug Net console it appears to do a 302 redirect to http://mydomain.com.au

This suggests its not finding the certificate activity and occurs when creating any new instances  of the Simple Certificate activity.

**Edit 2** - Turning on Debugging - no errors are shown

**Comment by bozoh** [comment]
*404- Not found*,  it's look like you don't have this file on your server
Is this plugin installed properly ?,  
mod/simplecertificate/view.php  exists in your installation?

If all perfect, firebug suggested a *site redirect (302)*, so there is any configuration redirecting to another place?
Like:
* URL rewrite rules 
* an inverse proxy configuration

**Comment by nikmav** [comment]
Problem solved.  Previous dev had the file permissions screwed up on the module.  Sorry to bother!

**Comment by bozoh** [comment]
ok, your problem can help others,  file permission problem, so server can't reach view.php file, causing an 404 error

**Comment by nikmav** [comment]
Yes 755 on dirs and 644 on files works - in this instance the dev had 777 on dirs and 666 on files.  Although these permissions were more open perhaps too open for php security

**Comment by bozoh** [comment]
look out the datadir permission too, 777 is not good for production sites,  i use 2770
