### ISSUE TITLE
Issued certificates missing after upgrade

### ISSUE THREAD

**Issue by heather-williams** [bozoh/moodle-mod_simplecertificate#132]
I have a site that was on Moodle 2.5.2 with simplecertificate version 2013092800 2.1.1 - the site was upgraded to Moodle 2.7.8 with simplecertificate version 2015061727 2.2.2 - after the upgrade the issued certificates no longer show via the UI, they all say "File not Found" - I believe this is because the new pathnamehash field in the mdl_simplecertificate_issues table is not populated with the pathnamehash. 

Is there a query that we can run to fix this?

**Comment by bozoh** [comment]
it's seems an upgrade problem,  the easy way do corrte this  put haschange=1 on mdl_simplecertificate_issues table

UPDATE mdl_simplecertificate_issues set haschange=1 where timedeleted is null

**Comment by heather-williams** [comment]
They are already set to haschange = 1 in the table. Should that have updated the pathnamehash? Is there something else we should do?

**Comment by bozoh** [comment]
with haschange all certificates will be regenerated when some one reissues them.  
You can go to bulk operation and reissues all of than
