### ISSUE TITLE
Serial Certificate numbers for a class & Customizing  text alignment

### ISSUE THREAD

**Issue by Afroozr** [bozoh/moodle-mod_simplecertificate#138]
Dear Carlos,
I am one of your Simple_certificate users for Moodle. Currently my moodle version is 2.9 and I am using release 2.2.3 of your plugin. Although this is so perfect, I have some problems while customizing the format and text alignment. 
My first  problem is that I have to print date of issue at the Top Left side of the certificate. I tried many times by inserting HTML in this area, but it isn't working. The module shows all of the texts in the middle of the page.
My second problem is with certificate numbers! Currently, they are being produced randomly and are a combination of numbers and characters. I need this number (only digits) to be unique and produced in a sequence. In other words, If I have 10 students in a class, and want to publish certificates for them, they must be like 5874569201 To 5874569210.

I would really appreciate it if you could guide me, or provide an update including these points.

Regards,
Afrooz Rashedi
E-Learning Specialist at Tikab

**Comment by bozoh** [comment]
Hello,  
Why not use the plugin's forum for this  questions ?
https://moodle.org/mod/forum/discuss.php?d=222296

For text position i suggest to use tables,  and the code is generated in locallib.php file, method  get_issue_uuid() (line 822)
