### ISSUE TITLE
Certificate background image & text content to plugin default settings

### ISSUE THREAD

**Issue by anieminen** [bozoh/moodle-mod_simplecertificate#142]
Hi,

Is it possible to add default image and certificate text fields to site level plugin settings? That way you could create a template to be used when adding a new simplecertificate activitity.

**Comment by bozoh** [comment]
You can create a meta course/course with  a simple certificate activity,  and import it in the courses you want.

This meta course/course with be a certificate templates,and better because you can have more then one template.
