### ISSUE TITLE
Feature request: Site-wide default template

### ISSUE THREAD

**Issue by Jarvil** [bozoh/moodle-mod_simplecertificate#143]
Hello,

I would like to see an feature where administrator/managers could create a sitewide default template (that includes Certificate Image File and Certificate Text) for the certificate-activity. 

The default template could be for example added to the page:

/admin/settings.php?section=modsettingsimplecertificate

Where you manage Simple certificate's site-wide settings.

Although this feature adds a default background image and text for every certificate-activity, teacher should still be able to modify background image and certificate text if he/she wishes so. So no "locking" it down.

*********
![certificate](https://cloud.githubusercontent.com/assets/15193418/13457359/72df6e66-e070-11e5-830a-e45ad7e7f650.PNG)

**Comment by bozoh** [comment]
i think answered this before,  it's better to create a meta course or a course with a certificate, and them import it to desired courses,  with this you can have more then one template
