### ISSUE TITLE
Fully hidden custom profile fields can be output to certificates

### ISSUE THREAD

**Issue by ebithell** [bozoh/moodle-mod_simplecertificate#161]
In plugin version 2.2.4, it is possible to output fully hidden (not visible to anyone) custom profile fields to certificates by using the appropriate placeholder code {PROFILE_<name_of_field>}. This may expose user information that should not be visible to teachers. For the same reason, I'm doubtful about request #144, which looks as if it could lead to the same problem. Would you be able to take a look at this?
Many thanks,
Erica

**Comment by bozoh** [comment]
@ebithell  comments in the original post please

**Comment by bozoh** [comment]
and sorry  this plugin do not support moodle 2.2  anymore,  it's still showing hidden custom profile field  in moodle 3.0, 3.1 or 3.2 ?

**Comment by ebithell** [comment]
Hi, many thanks for looking into this. I've tested your plugin in both Moodle 3.0 and 3.2 (with your latest plugin version), and had this issue in both versions.

**Comment by ebithell** [comment]
I've had a further look at this, and have found that the issue only occurs if the user who issues the certificate has permission to see the hidden field (e.g. has a Manager role). It remains a problem because this role might be given to course administrators and (once created), the certificate is visible by the student themselves and all teachers in the course, but it's less worrying than if this could be done by teachers.

It looks as if the inclusion of hidden fields takes the permissions of the creating user, whereas perhaps it ought to be the lowest capability associated with users who have 'view' permissions.

**Comment by bozoh** [comment]
If more people  get interested  and send suggestion, votes in preferred issues (the smile face),  bugs report, or contribute with some code (a dream),  the plug in  could evolute quicker 

So,  I thanks you,  a lot

**Comment by bozoh** [comment]
The code already  do the checks, but if the users have  moodle/user:viewalldetails or moodle/user:viewall    enabled  they will see hidden profiles.
You can  overide this permissions in the activity to avoid this.

If you testting using admin/manager accounts,  all profiles fields will be visible
