### ISSUE TITLE
Restriction "must be complete with pass grade" doesn't work.

### ISSUE THREAD

**Issue by Jarvil** [bozoh/moodle-mod_simplecertificate#168]
Hello,

the restriction "must be complete with pass grade" doesn't work in Simple Certificate -plugin.

1. Create a quiz with "Grade to pass" as 10.0 and "Show activity as complete when conditions are met" and "Require passing grade" and make some question.
2. Create a simple certificate on the course and under "Restrict access" add restrcition "activity completion" choose the quiz and select "must be complete with pass grade"
3. Do the quiz with a student with grade 10,0
4. Notice how you cannot access the Simple certificate

If you change the restriction in Simple certificate to "must be marked complete" student can open the certificate.

This concerns Moodle 3.1.4 and mod_simplecertificate 2016062231

**Comment by Jarvil** [comment]
Hello,

This seem to concers basic moodle activities like Workshop

**Comment by bozoh** [comment]
Looks like a bigger issue,  related to moodle API, not the plugin code.
I'm follow this issue at moodle tracker too.

Thanks @Jarvil

**Comment by bozoh** [comment]
well,  was fixed... since it's not a plugin bug
