### ISSUE TITLE
Centered text isn't displayed centered on the certificate

### ISSUE THREAD

**Issue by Jarvil** [bozoh/moodle-mod_simplecertificate#174]
Hello,

When I;

1. Write a text in "Certificate Text"-field 
2. Select the text and click "Center" from the ATTO-texteditor it goes to the center
3. Then I save and close
4. Next I press "Get certificate" 
5. The text isn't in the center of the page but in the right corner.
6. If I open the certificate settings again the text is displayed in the center

So this is a bug when "center" doesn't center it on the certificate.

![bugi1](https://cloud.githubusercontent.com/assets/15193418/26307891/7da59d36-3eff-11e7-9b37-2cb2bef52963.PNG)

![bugi2](https://cloud.githubusercontent.com/assets/15193418/26307839/45a8e6e0-3eff-11e7-97fc-0cf63e6a136c.PNG)

**Comment by bozoh** [comment]
as i have told in plugin forum,  and in plugin documentation,  use tables for text positioning and margins
