### ISSUE TITLE
Simper Certificate activity not deleting

### ISSUE THREAD

**Issue by cybercpted** [bozoh/moodle-mod_simplecertificate#175]
I have a problem with a new activity of Simple Certificate refusing to delete using the . It will also not transfer to a different section and it will not allow me to delete the section either (I tried making it the last section and deleting that - unsucessfully).
At different points in Moodle (depending on task)  it shows a popup message 'Activity deletion in progress' and has done so for the last 48 hours.
Using debug, the error codes when I click delete to delete the Simple Certificate activity are are:
* line 2880 of /lib/moodlelib.php: moodle_exception thrown
* line 56 of /course/rest.php: call to require_login()
I welcome your advice on deleting the activity  of simple certificate
Best wishes, Terence

**Comment by bozoh** [comment]
Everything  works fine here,   moving to another section and removing the activity.

You can test in my dev site  http://www.dev-moodle.ml

the debug messages  is point to moodle's core files,  not to my plugin file (my file is under the folder mod/simplecertificate).

i think could be some installation error

**Comment by cybercpted** [comment]
Many thanks for your prompt reply.
The solution turned out to be straightforward. I deleted the simple certificate plugin and it removed the problem entries  in the section(s) and allowed the sections to delete.
Perhaps this could be in FAQs?
Terry
