### ISSUE TITLE
Any user can execute bulk actions adding the "tab" number in the URL

### ISSUE THREAD

**Issue by davidherney** [bozoh/moodle-mod_simplecertificate#179]
Hi bozoh...

If a user (student) put the "tab" number in the URL he can access the bulk operations like download/build all certificates or download users list.

It is a relatively high security problem.

Saludos

**Comment by bozoh** [comment]
this patch will solve the problem 
https://gist.github.com/bozoh/a282badf56ffa7da0c4f1ec3d85a0af7

I think this patch could be applied in  2.7x and above,   i have successfully applied in 3.1, 3.2 and 3.3 moodle version

**Comment by davidherney** [comment]
It's right

Thanks
