### ISSUE TITLE
Bitwise shifts by negative number will throw an  ArithmeticError in PHP 7.0

### ISSUE THREAD

**Issue by 2shediac** [bozoh/moodle-mod_simplecertificate#184]
Hi - while doing a quick review of your plugin for use in Moodle 3.3, our automated code checks found the following error:

Bitwise shifts by negative number will throw an  ArithmeticError in PHP 7.0.

This occurs in lib/fpdi/filters/FilterLZW.php line 147.

Can we ask that you check this and let us know if its a problem and if it needs to be corrected / adjusted.

**Comment by bozoh** [comment]
This is not part of my plugin,  it's a lib which my plugin uses  and this lib will be removed in the next version.
