### ISSUE TITLE
Certificate not generated if images is used

### ISSUE THREAD

**Issue by marializ** [bozoh/moodle-mod_simplecertificate#186]
Hello, could you investigate this https://moodle.org/mod/forum/discuss.php?d=222296#p1471186 ?
If certificate has text and images and you click Generate Certificate it shows error Exception - getimagesize(xxxxx): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
If images is removed from certificate text editor and only text left - certificate is generated successfully.

**Comment by bozoh** [comment]
See
https://moodle.org/mod/forum/discuss.php?d=222296#p1471615
