### ISSUE TITLE
Bitwise shifts in PHP7

### ISSUE THREAD

**Issue by 2shediac** [bozoh/moodle-mod_simplecertificate#188]
Hi - in a previous posting you indicated that the error that we found Bitwise shifts by negative number will throw an ArithmeticError in PHP 7.0.

This occurs in lib/fpdi/filters/FilterLZW.php line 147.

will be fixed in the next version of the library - do you have a release time line for this?

Or can we send you a patch until you get the updated version of the library?

Thanks

**Comment by bozoh** [comment]
This is a 3th party lib, not mine,  it's old,  and i this is will be removed in the next version.
Moodle has added this lib in yours code base,  so no need  to add this in the plugins code base anymore
