### ISSUE TITLE
Alternative email name is not working

### ISSUE THREAD

**Issue by bozoh** [bozoh/moodle-mod_simplecertificate#191]
It not saving the configuration, see more in:
https://moodle.org/mod/forum/discuss.php?d=230459#p1487446

**Comment by heather-williams** [comment]
I am also experiencing this issue. When you populate the Email From Name, it does not save.

**Comment by bozoh** [comment]
another with same issue
https://moodle.org/mod/forum/discuss.php?d=222296#p1518847

**Comment by bozoh** [comment]
another with same issue
https://moodle.org/mod/forum/discuss.php?d=222296#p1518847

**Comment by bozoh** [comment]
Can't  reproduce in moodle 3.9dev,   Teacher's and admin's certificates are not sent at all

To Teachers e-mail
![image](https://user-images.githubusercontent.com/2317639/79069703-b0bfda00-7ca6-11ea-9f0f-304a62dae059.png)

To other email 01
![image](https://user-images.githubusercontent.com/2317639/79069725-dd73f180-7ca6-11ea-9c0b-fd2e4a93836b.png)

To other email 02

![image](https://user-images.githubusercontent.com/2317639/79069740-f67ca280-7ca6-11ea-885b-9126de129482.png)
