### ISSUE TITLE
Certificate won't open in IE11

### ISSUE THREAD

**Issue by matthewvryan** [bozoh/moodle-mod_simplecertificate#200]
Receive error when generating the certificate in IE11 says " file does not being with '%PDF-' Https://www.XXXX.com/mod/simplecertificate/view.php?id=740&action=get

It is an adobe reader issue...see this https://helpx.adobe.com/acrobat/kb/pdf-error-1015-11001-update.html

SOLUTION
- Fix certificate generation to address extra header validation in IE11 / Adobe 11.

**Comment by bozoh** [comment]
all pdf file begins with %PDF,  so, first
Test if you can open it  in other programs besides browse,  (acrobat reader, for example) if won't open there is something wrong  in your instillation,  it's output some error message during the pdf generation, causing this problem.

Can you attach the generate pdf file here?

**Comment by matthewvryan** [comment]
[Module_4_Delivering_a_Palliative_Approach_for_Aged_Care_in_the_Community_Setting-Module_4_Delivering_a_Palliative_Approach_for_Aged_Care_in_the_Community_Setting_Course_Completion_Certificate_39057.pdf](https://github.com/bozoh/moodle-mod_simplecertificate/files/2161679/Module_4_Delivering_a_Palliative_Approach_for_Aged_Care_in_the_Community_Setting-Module_4_Delivering_a_Palliative_Approach_for_Aged_Care_in_the_Community_Setting_Course_Completion_Certificate_39057.pdf)

**Comment by matthewvryan** [comment]
Sorry...I accidentally closed this...how do you reopen?

So I can product the certificate using Chrome, but not from Internet Explorer.

**Comment by matthewvryan** [comment]
And these are two certificates produced via IE11 one as Admin and One as Logged In User. I know it should not matter as the server produces the PDF, but thought I would include anyways.
[Certificate Produced in IE11 as Admin.pdf](https://github.com/bozoh/moodle-mod_simplecertificate/files/2161700/Certificate.Produced.in.IE11.as.Admin.pdf)
[Certificate Produced in IE11 Logged in as User Chelsea.pdf](https://github.com/bozoh/moodle-mod_simplecertificate/files/2161701/Certificate.Produced.in.IE11.Logged.in.as.User.Chelsea.pdf)

**Comment by bozoh** [comment]
All pdf files has no error  (opens without any errors), i can't see any errors inside the file, and has    
`%PDF-`  header, as is valid is PDF validation tools.  So  it's not a plugin bug or anything that i can fix ...

![pdf](https://user-images.githubusercontent.com/2317639/42274400-ee74913a-7f62-11e8-846b-257a4902566e.png)

![pdf2](https://user-images.githubusercontent.com/2317639/42274445-1953cb3c-7f63-11e8-8a43-e0f27c7c2dbf.png)

**Comment by matthewvryan** [comment]
Hi Carlos...thanks for looking at these PDF's. I am still having the problem of not being able to load certificates which makes it difficult for me to give you a pdf with the problem. The problem only occurs for users, it does not happen with admins. What is the process for SimpleCertificate to generate the certificate when the user clicks the "Get Certificate" button. This might help me resolve the issue on our server.

**Comment by matthewvryan** [comment]
But the second time I generate the certificate it generates the certificate correctly.

**Comment by bozoh** [comment]
The server is output errors messages during pdf generation,  and this error goes to pdf file, make it invalid (broking it),  if you change the file station on Broken pdf.pdf  to Broken pdf.html  and open it in browser you can see the error.

The error is your DB  it's getting 2 (or more)  enroll records  when it's expected only one, it's related with those line (in the code):
https://github.com/bozoh/moodle-mod_simplecertificate/blob/master/locallib.php#L1413-L1427

![pdf1](https://user-images.githubusercontent.com/2317639/42325082-859f9f68-803b-11e8-9794-317684ffb1b7.png)


![pdf2](https://user-images.githubusercontent.com/2317639/42325090-8b63ce4c-803b-11e8-904c-38c48e8aba1c.png)
