### ISSUE TITLE
coursename field incorret when import course

### ISSUE THREAD

**Issue by giselebrugger** [bozoh/moodle-mod_simplecertificate#205]
**Describe the bug**
when i import a certificate from a course the coursename field in the table  mdl_simplecertificate remains the same as the original course

see here too:  https://moodle.org/mod/forum/discuss.php?d=370301#p1495398

**Moodle Version(s)**
moodle 2.9.1

**To Reproduce**
1. import an certificate from other course
2. create a test certificate
3. see the **name file to download** in PDF 
4. the name is a old course

is the coursename in table mdl_simplecertificate no update in import

**Comment by bozoh** [comment]
i think it's related to #101

**Comment by giselebrugger** [comment]
Thank you @bozoh . 
Can we suggest a more complete text to be displayed on the button? (help) for this field: alternative course name.
Explain that the course's alternate name + certificate name will compose the name of the PDF file that will be generated for download.

**Comment by giselebrugger** [comment]
suggestion accepted in help button translation in https://lang.moodle.org/local/amos/contrib.php?id=24746

**Comment by bozoh** [comment]
I think i begin to understand this issue, and after read the discussion with more attention i think it's not only the filename name issue,  i will re-open this and put it in the to  verify

**Comment by bozoh** [comment]
well,  i can't reproduce this,  the file name was right,  i think it's a already fixed issue (as mentioned),  and if you use  alternative course name settings, this will be imported to the new course (of course!),  you must change if you don't what to use it.
