### ISSUE TITLE
Error while creating Simple Certificate activity in moodle 3.5.1

### ISSUE THREAD

**Issue by Sudhanshu0044** [bozoh/moodle-mod_simplecertificate#206]
While creating activity using "Simple Certificate" in moodle 3.5.1 I am facing issue in it.
Error code I am receiving is

"Exception - Argument 1 passed to file_get_all_files_in_draftarea() must be of the type integer, null given, called in [dirroot]/lib/form/filemanager.php on line 336"

I have attached error screen below.
![screenshot from 2018-07-31 17-34-57](https://user-images.githubusercontent.com/38027574/43822087-afd43270-9b08-11e8-912a-977bfdde72e1.png)

1. Install Simple Certificate plugin in moodle 3.5.1.
2. Create an activity using simple certificate.
3. After filling the user fields & finally click on Saving & changes

Here we expect that activity will successfully created.

**Comment by bozoh** [comment]
which version on plugin ?

**Comment by bozoh** [comment]
i can't  reproduce this,  have created  many certificates with  images, without images and works as expected

1. Which plugin version ?
2.  which php version?
3. can you turn on moodle's debug mode, and post the full error log ?

**Comment by Sudhanshu0044** [comment]
1. I am using "Simple Certificate 2.2.8 (2018080400) - on Moodle 3.5"
2. Using php 7.1 version
3. Turning on the debug mode I am getting error 
![screenshot from 2018-08-08 11-12-36](https://user-images.githubusercontent.com/38027574/43877456-904aab50-9bb7-11e8-8ce1-a369b61c743d.png)

**Comment by bozoh** [comment]
i created a issue report in moodle tracker site,  it's seems not be realted to my code but some changes in moodle_34 and moodle_35

please vote into it
https://tracker.moodle.org/browse/MDL-63180

**Comment by bozoh** [comment]
i created a issue report in moodle tracker site,  it's seems not be realted to my code but some changes in moodle_34 and moodle_35

please vote into it
https://tracker.moodle.org/browse/MDL-63180
