### ISSUE TITLE
Could you use different releasenumbers for different version releases?

### ISSUE THREAD

**Issue by Jarvil** [bozoh/moodle-mod_simplecertificate#207]
Hello,

It would be great if in the future you could use different plugin releasenumbers for different Moodle versions. 

At the moment you use the same releasenumber for different Moodle versions f.ex.

2.2.8 ***_(2018082000)_*** Moodle 3.5
2.2.8 ***_(2018082000)_*** Moodle 3.4

Different releasenumber would help automated installing of the plugin with Moodlegist. See this as reference;

https://github.com/CLAMP-IT/moodlegist/issues/3

**Comment by bozoh** [comment]
well  i will start put the moodle verison in last 2 numbers    
2018082000 -> 2018082035 for moodle 3.5
2018082000->2018082034 for moodle 3.4

**Comment by Jarvil** [comment]
Thank you.
