### ISSUE TITLE
Group filter not automatically applied when viewing 'issued certifcates'

### ISSUE THREAD

**Issue by davefoord** [bozoh/moodle-mod_simplecertificate#212]
When viewing the 'issued certificates' page, if you select a group from the dropdown, it doesn't apply the filter for that group, however if you refresh the screen it then does apply the filter correctly. Can this be changed so that the process of selecting the group, automatically filters for that group?

Moodle Version
Moodle 3.4.2+ (Build: 20180405)

Simple certificate version 2.2.8 (2018082000)

**Comment by bozoh** [comment]
Can't reproduce in moodle 3.9 dev, it's refreshing without problems
