### ISSUE TITLE
Verify not working!

### ISSUE THREAD

**Issue by behoof** [bozoh/moodle-mod_simplecertificate#219]
**Describe the bug**
The verify page doesn't work

**Moodle Version(s)**
Moodle 3.5 (Build: 20180517) and Simple Certificate 2018082000

**To Reproduce**

1. Visit the site with QR code. 
2. Click on recaptcha
3. Click on verify

Nothing happens! Recaptcha field is empty now.

**Comment by valentephd** [comment]
@behoof I have the same problem.

After I put the code in verify.php and validate reCaptcha, nothing happens.

You did get solved this problem ??

**Moodle Version**: 3.5.4
**Simple Certificate**: 2.2.8 (2018082000)

**Comment by bozoh** [comment]
happens when  user is not logged in
