### ISSUE TITLE
Different version number of different releases?

### ISSUE THREAD

**Issue by Jarvil** [bozoh/moodle-mod_simplecertificate#220]
Hello,

Could you consider in the future using different version number for different releases? This would help automated installations. I'm referring the number between () at:

https://moodle.org/plugins/pluginversions.php?plugin=mod_simplecertificate

F.ex these could be different:
2.2.8 **(2018082000**)Moodle 3.4
2.2.8 **(2018082000**)Moodle 3.5

**Comment by Jarvil** [comment]
@bozoh

**Comment by Jarvil** [comment]
for more information see this: https://github.com/CLAMP-IT/moodlegist/issues/3

**Comment by bozoh** [comment]
i think if i put the moodle version at the end  i.e:
2.2.8 (2018082034)Moodle 3.4
2.2.8 (2018082035)Moodle 3.5

**Comment by Urpokarhu1** [comment]
Hello

That sounds great.
