### ISSUE TITLE
Incorrect list of issued certificates

### ISSUE THREAD

**Issue by jaclecavalier** [bozoh/moodle-mod_simplecertificate#232]
**Describe the bug**
The list of issued certificates is not complete, and the list of students meeting the conditions is also not complete.

**Moodle Version(s)**
3.5

I need to re-issue a certificate for a learner who had incorrectly filled in his profile, and cannot do so with these incomplete/incorrect lists. When I try to log in as the learner and generate the certificate that way, it opens the previous certificate with the unmodified profile details.

Is there a way to update/refresh the lists of issued certs and learners meeting conditions? Or alternatively, a relatively easy way (without going into the DB) to delete a certificate so it can be issued anew?

**Desktop (please complete the following information):**
 - Win 10
 - IE 11 or Chrome 79

thanks.
Jacques

**Comment by bozoh** [comment]
As i have told **MANY times  in plugin forum**, this is not a bug.  It's prevent some one changes his/her profile name (for example)  and issue a certificate to some one else.

To reissue the certificate  you only need to  make a change on certificate activity (put a white space on certificate text, for example) and save it
