### ISSUE TITLE
Add new course custom field in certificate

### ISSUE THREAD

**Issue by bhodeler** [bozoh/moodle-mod_simplecertificate#241]
Hello,

I´ve added a new course custom field, "coursehours", which store course hour number.

My issue is I don´t know how collect that info to include in my certificate.

Can you help me, please?

**Comment by bozoh** [comment]
and your course have variable course hours ? if not only add a text in the certificate,  otherwise you will need to change the code, in this function:
https://github.com/bozoh/moodle-mod_simplecertificate/blob/master/locallib.php#L1344
