### ISSUE TITLE
Links are not clickable in PDF certificate

### ISSUE THREAD

**Issue by COns** [bozoh/moodle-mod_simplecertificate#249]
**Describe the bug**
When I include links (both as text or image), they are displayed in the text-editor, but not in the generated/issues PDF certificate.
I need to include links in PDF certificate to validate generated certificates.

**Moodle Version(s)**
The moodle version Moodle 3.9.1 

**To Reproduce**
1. Add a link (either text or image link) in the text editor of the simplecertificate,
2. Click on 'Save and return to course' button.
3. Click on the simple certificate
4. Click on 'Get Certificate' button.
5. Check your email and open the emailed certificate
6. Try to click on the link you entered, the link DOES NOT work! 

**Expected behavior**
All added links (text or image) should be clickable in PDF certificate

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser:  Chrome 97

**Additional context**
Where and how can we add links ?

**Comment by srssaulo** [comment]
hi, i did a alteration to fix this. Pull request link https://github.com/bozoh/moodle-mod_simplecertificate/pull/253
a tag was forbidden

**Comment by bozoh** [comment]
There is a close bug related to this feature 
Issue https://github.com/bozoh/moodle-mod_simplecertificate/issues/111

I don't know if i approve this PR it's going to re-open this bug (auto-llink)

Can you test it ?, enabling auto link feature in you moodle
