### ISSUE TITLE
{USERNAME} attribute changes to another user after changing delivery-method!

### ISSUE THREAD

**Issue by Urpokarhu1** [bozoh/moodle-mod_simplecertificate#260]
**Describe the bug**
{USERNAME} attribute changes to another user after changing delivery-method! 

**Moodle Version(s)**
Moodle 3.9
mod_simplecertificate 2.2.10 (2020041238)

**To Reproduce**
0. Create simple certificate with certificate text that has {USERNAME} and delivery method "open in a new window"
1. Open simplecertificate as a student
2. As administrator go to "issued certificates" -> open issued certificate PDF -> notice how {USERNAME} is the students user name
3. As administrator go to simple certificate settings and change delivery to "email"
4. As administrator  go to "issued certificates" -> open issued certificate PDF -> notice how {USERNAME} now the administrator user name, not the students

**Expected behavior**
{USERNAME} should stay as student username even when changing delivery method.

**Comment by bozoh** [comment]
I don't  think it's a bug

1- Any changes in certificate configuration makes all certificate to be invalidated, by   setting a reissued flag to all certificates
2- Only students certificates  is saved, (admin, teachers ... is not saved), so this  admin certificate will not  be issued to  students.

I think  if you go to bulk operations and  click  issue all  (anything like that),  and after  that  go to issues certificate, it will display the right certificate data

**Comment by Urpokarhu1** [comment]
Hello,

Why would changing delivery method invalidate certificates?
