### ISSUE TITLE
Plugin for Moodle 4.1.2

### ISSUE THREAD

**Issue by alejimenez2** [bozoh/moodle-mod_simplecertificate#261]
**Is your feature request related to a problem?
We would like to have this plugin upgraded to Moodle's lastest version 4.1.2

**Comment by davidherney** [comment]
I'm working on a stable version for Moodle 4.1. You can get it from https://github.com/davidherney/moodle-mod_simplecertificate/

I will try to review the issues that were reported here, but I will attend to the new ones in my fork (https://github.com/davidherney/moodle-mod_simplecertificate/issues)

Saludos

**Comment by davidherney** [comment]
Hi @bozoh ...

Of course. I would be honored if you add me to the plugin site in moodle as a maintainer. I try to keep it updated as long as possible.

Would you prefer the main branch to stay on your GitHub account or mine? As you prefer.

Saludos

**Comment by luisdev** [comment]
This might help:
https://moodledev.io/general/community/plugincontribution/adoption

**Comment by danmarsden** [comment]
Hi @bozoh , I'm happy to transfer ownership of the plugins db entry to David if you could confirm you are happy for me to do that! I note he's also posted about this in the moodle.org forums too!

**Comment by bozoh** [comment]
Yes you can transfer it

**Comment by bozoh** [comment]
I added @davidherney as collaborator

**Comment by danmarsden** [comment]
great thanks @bozoh - I've just set David as the Lead maintainer on the plugins db entry now as well!
