### ISSUE TITLE
Failed opening required '.../Horde/Support/Uuid.php' with Moodle 4.4

### ISSUE THREAD

**Issue by leonstr** [bozoh/moodle-mod_simplecertificate#267]
**Describe the bug**
When attempting to view the certificate with mod_simplecertificate 2024051101 and Moodle 4.4 the following error occurs:

Exception - Failed opening required '[dirroot]/lib/horde/framework/Horde/Support/Uuid.php' (include_path='[dirroot]/lib/pear:.:/usr/share/pear:/usr/share/php')

More information about this error
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 847 of /mod/simplecertificate/locallib.php: Error thrown
    line 619 of /mod/simplecertificate/locallib.php: call to simplecertificate->get_issue_uuid()
    line 1969 of /mod/simplecertificate/locallib.php: call to simplecertificate->get_issue()
    line 122 of /mod/simplecertificate/view.php: call to simplecertificate->view_default()

See also [this forum reply](https://moodle.org/mod/forum/discuss.php?d=222296#p1841437).

**Moodle Version(s)**
Moodle version 4.4+ (Build: 20240516).

**To Reproduce**
1. Create a course.
2. Add a mod_simplecertificate instance.
3. From the course page click on the mod_simplecertificate instance.
4. Click the _Get certificate_ button.

**Expected behavior**
The certificate is displayed.

**Screenshots**

![simplecerterror](https://github.com/bozoh/moodle-mod_simplecertificate/assets/10348217/24317e52-b774-4950-839f-a897c0cad90e)

**Desktop (please complete the following information):**
 - Fedora Linux 38.
 - Firefox
 - 125.0

**Comment by matestaweb** [comment]
Hola, se ha solucionado este error?

**Comment by bozoh** [comment]
Since there is no more support to UUID,  why not change the alg. which generate the certificate code to nanoid

**Comment by ivosnabl** [comment]
Please upgrade plugin, we strongly need compatibility to Moodle 4.4!!!

**Comment by jheenan** [comment]
We are also experiencing this issue on our Moodle 4.4s

**Comment by davidherney** [comment]
Hi...

I have created a branch with compatibility with Moodle 4.4+. Please test it and give me your feedback:
https://github.com/bozoh/moodle-mod_simplecertificate/tree/tk_moodle404_compatibility

Saludos

**Comment by ivosnabl** [comment]
It works in first test, thank you!

**Comment by Indigita2024** [comment]
Thank you very much for this patch. It works well!

**Comment by davidherney** [comment]
Officially released.
