### ISSUE TITLE
Moodle 4.3 - Exception - mysqli::real_escape_string(): Argument #1 ($string) must be of type string, array given

### ISSUE THREAD

**Issue by PaulFlanders** [bozoh/moodle-mod_simplecertificate#282]
**Describe the bug**
Installing current version of simple certificate to clean Moodle 4.3 and 4.4 produces error " Exception - mysqli::real_escape_string(): Argument #1 ($string) must be of type string, array given" when saving. 

Appreciate there is no 4.3 or 4.4 version available as yet but this might help someone who needs the plugin to function after an upgrade from 4.1.

**Fix**
Error resides in the certificate back page which is sending as an array

Open locallib.php and change the following 

Remove 

```
       if (isset($formdata->secondpagetext['text'])) {
            $update->secondpagetext = $formdata->secondpagetext['text'];
            if (!isset($formdata->secondpagetextformat)) {
                $update->secondpagetextformat = $formdata->secondpagetext['format'];
            }
            unset($formdata->secondpagetext);
        }
```

Replace with

```
        if (isset($formdata->enablesecondpage) && $formdata->enablesecondpage == 1) {
            // Only process secondpagetext if the second page is enabled
            if (isset($formdata->secondpagetext['text']) && !empty($formdata->secondpagetext['text'])) {
                // If second page text exists, process it
                $update->secondpagetext = $formdata->secondpagetext['text'];
                $update->secondpagetextformat = $formdata->secondpagetext['format'];
            } else {
                // If no text, set default values
                $update->secondpagetext = '';
                $update->secondpagetextformat = 1; // Or any default format
            }
        } else {
            // If second page is not enabled, make sure no second page text is saved
            $update->secondpagetext = null;
            $update->secondpagetextformat = null;
        }
        
        // Always unset secondpagetext after processing to avoid issues
        unset($formdata->secondpagetext);
```

**Comment by davidherney** [comment]
Hi @PaulFlanders...

A few days ago I created a compatibility branch for Moodle 4.4. Today I integrated it into the main branch. What you mentioned has changed. Please try this new version and tell me if everything is OK or if you notice any bugs.

Gracias

Saludos

**Comment by PaulFlanders** [comment]
Hi @davidherney 

Thanks for the update, the new main branch installed and worked perfectly. 

No bugs noticed as yet, great work.

Paul
