### ISSUE TITLE
"Issued Certificates" page issue

### ISSUE THREAD

**Issue by nauticalist** [bozoh/moodle-mod_simplecertificate#98]
Hi,

On the "Issued Certificates" page it displays "File not found" error if the certificate is created with bulk operations option. Other delivery options are working fine.
![2014-08-06 23_58_49-baar belgesi](https://cloud.githubusercontent.com/assets/5111449/3834014/950752b6-1dac-11e4-9004-93818ddde525.png)

**Comment by bozoh** [comment]
Add issued certificate creation after one pdf file processed
